### PR TITLE
Fixes for Apache Kafka trademark usage

### PR DESCRIPTION
**Pull request by fbricon**

### CODE REVIEW

**Comment by fbricon** [comment]
@jlandersen it's highly probable the extension name "Kafka", doesn't comply with the Apache Kafka trademark usage. 

I suggest we rename it to something along the lines of "Tools for Apache Kafka", or anything else, that doesn't imply this project is a part of the upstream Apache Kafka project

**Comment by jlandersen** [comment]
Sounds right :) https://kafka.apache.org/trademark
Thanks for pointing it out

**Comment by fbricon** [comment]
Well I wanted to discuss renaming the project, before merging the PR, but the merge doesn't hurt ;-)

**Comment by fbricon** [comment]
BTW, you'll need to update the about blurb on the https://github.com/jlandersen/vscode-kafka frontpage too

**Comment by jlandersen** [comment]
;) I realized that the second I merged it.

Do you know someone who might be able to clear it up? As mentioned before, as I read the trademark page and https://www.apache.org/foundation/marks/ (without going into the full details) the disclaimer should be sufficient. Likelihood of confusion should be minimal as I see it as well, especially considering the publisher name on the marketplace is my name.

**Comment by fbricon** [comment]
I have asked @pmuir to check with someone at the ASF

**Pull request merged**
