### PR TITLE
New SASL/SCRAM support

### LINKED ISSUE #3: Add support for SASL/SCRAM
Hi,

Do you intend to implement SASL_SSL (particularly SASL_SCRAM) connectivity ? 

Thanks.

### PR DESCRIPTION
**Pull request by fbricon**
Added SASL/SCRAM-256 and SASL/SCRAM-512 authentication mechanisms:
 
Screenshot 2021-01-05 at 18 40 26

Tested against a https://www.cloudkarafka.com/ cluster (Free Tier) :
- connection works (using SCRAM-256)
- listing brokers, topics, consumer group works
- producing messages works
 
Screenshot 2021-01-05 at 18 39 47

There are some things that still don't work against the karafka clusters:
- creating a topic fails (looks like authorization limitation), even when using the user prefix for the topic name
- ~~adding/starting a consumer fails (complains about SASL mechanism not supported)~~ fixed

Fixes #3

### CODE REVIEW

**Comment by fbricon** [comment]
The consumer issue was fixed. 
AFAICT, everything works as expected.

**Comment by dentarg** [comment]
> creating a topic fails (looks like authorization limitation), even when using the user prefix for the topic name

Have you tried prefixing consumer group name with the username? https://github.com/CloudKarafka/python-kafka-example/commit/365850e67ef6fc41f8a98c67445b611d254a5484

**Comment by fbricon** [comment]
@dentarg on cloudkarafka, topic creation fails, even with the username prefix. But I could reproduce the same behaviour with a simple java client.
Consumer creation works, even without the username prefix

**Comment by fbricon** [comment]
CloudKarafka said everything works on their instances: https://twitter.com/CloudKarafka/status/1350071031336153089
I think we're good to go.

**Comment by angelozerr** [comment]
Works like a charm with my cloudkafka cluster, great job @fbricon !

**Pull request merged**
