### PR TITLE
Add 'Delete Topic' command

### LINKED ISSUE #24: Add ability to remove topics
Selecting a topic in the kafka explorer, there should be a `Delete Topic` menu, that'd display a confirmation message before actually removing the topic

### PR DESCRIPTION
**Pull request by fbricon**
Fixes #24

Setting as a draft PR because I don't understand why the topics are regenerated on my kafka cluster, after being properly deleted.

### CODE REVIEW

**Review by jlandersen — CHANGES_REQUESTED** [review]
Looks good - can you add the new feature to the changelog draft as well?

Something else to consider - I don't know if we want to require a confirmation on the user side before deleting a topic?

**Comment by fbricon** [comment]
You're absolutely right, I should have added a confirmation step. Will do, as well as update the changelog.

As for the zombie topic issue, looks like having the clustered configured with `auto.create.topics.enable:true` might be the issue:  https://stackoverflow.com/questions/46949188/kafka-topic-is-getting-reappeared-after-10-sec-of-deletion

**Comment by fbricon** [comment]
Screenshot 2020-12-07 at 18 02 30

**Comment by jlandersen** [comment]
> You're absolutely right, I should have added a confirmation step. Will do, as well as update the changelog.
> 
> As for the zombie topic issue, looks like having the clustered configured with `auto.create.topics.enable:true` might be the issue: https://stackoverflow.com/questions/46949188/kafka-topic-is-getting-reappeared-after-10-sec-of-deletion

Re the zombie topic issue - was there perhaps a producer and/or consumer alive at the time? Even with the setting on it should be deleted unless some client is making use of the topic (we could consider showing an info message if the setting is enabled - the config should be accessible from any of the broker configs)

**Comment by fbricon** [comment]
No I can see the same issue when creating/deleting topics from conduktor, even without adding consumers

**Comment by fbricon** [comment]
Problem is the topic recreation is inconsistent.

**Comment by fbricon** [comment]
That might not be the best typescript code (I'm a Java guy), but it works:

Screenshot 2020-12-07 at 22 26 22

**Pull request merged**
