### PR TITLE
Use waring icon instead of error for invalid cluster

### PR DESCRIPTION
**Pull request by angelozerr**
Use warning icon instead of error for invalid cluster

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Here the result (see waring icon after BAD codelens):

image

**Comment by fbricon** [comment]
please fix the typo in the commit message "Use warning icon..."

**Comment by angelozerr** [comment]
> please fix the typo in the commit message "Use warning icon..."

fixed

**Comment by fbricon** [comment]
thx @angelozerr

**Pull request merged**
