### PR TITLE
Enable/Disable fields wizard.

### PR DESCRIPTION
**Pull request by angelozerr**
Enable/Disable fields wizard.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR manage enabled/disabled 

 * state for SSL fields:

image

image

 * SASL fields.

image

image

**Comment by angelozerr** [comment]
I have the problem with focus lost like https://github.com/redhat-developer/vscode-wizard/issues/74

**Comment by angelozerr** [comment]
@fbricon you can review the PR, I'm using now the vscode-wizard 0.2.18 which has been released yesterday with some enabled field fixes.

**Comment by fbricon** [comment]
Works great, thanks!

**Pull request merged**
