### PR TITLE
Improve Starting, Stopping consumer codelenses.

### PR DESCRIPTION
**Pull request by angelozerr**
Improve Starting, Stopping consumer codelenses.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
The main idea of this PR is to delay the started and stopped status in order to codelens have time to refresh them.

Here a demo:

StartStopConsumerDemo

**Comment by fbricon** [comment]
How is being so fast you don't see the transitions an issue? 
We generally strive to decrease latency, not the opposite (even if just perceived)

**Comment by angelozerr** [comment]
> How is being so fast you don't see the transitions an issue?

Yes the fire of starting and started states are done too quickly and codelenses have no time to display the Starting... codelens.

> We generally strive to decrease latency, not the opposite (even if just perceived)

Ok.

**Comment by angelozerr** [comment]
I give up this PR.

**Pull request closed without merging**
